import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { FaFacebook } from "react-icons/fa";
import { FaTwitterSquare } from "react-icons/fa";
import { FaSquareInstagram } from "react-icons/fa6";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* Default Footer Section */}
        <footer className="bg-white text-gray-600 rounded-3xl py-8 border-4 border-gray-800">
          <div className="container justify-center items-center mx-auto px-4">
            <div className="flex flex-col md:flex-row md:justify-between md:items-start md:space-x-24">

              {/* Left Section */}
              <div className="mb-8 md:mb-0 flex flex-col items-start">
                <img src="/path-to-logo/logo.png" alt="Logo" className="mb-4" />
                <div className="flex space-x-4 mb-4">
                  <a
                    href="https://instagram.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="hover:text-black transition-colors"
                  >
                    <FaSquareInstagram className="w-6 h-6" />
                  </a>
                  <a
                    href="https://facebook.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="hover:text-black transition-colors"
                  >
                    <FaFacebook className="w-6 h-6" />
                  </a>
                  <a
                    href="https://X.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="hover:text-black transition-colors"
                  >
                    <FaTwitterSquare className="w-6 h-6" />
                  </a>
                </div>
                <a
                  href="mailto:davidbukolafoundation@gmail.com"
                  className="text-black transition-colors"
                >
                  davidbukolafoundation@gmail.com
                </a>
              </div>

              {/* Right Section */}
              <div className="flex flex-col space-y-8 md:text-left md:flex-grow">
                
                {/* First Row - Navigation Links */}
                <nav className="flex flex-col md:flex-row gap-12 md:justify-start">
                  <Link
                    href="/home"
                    className="text-black transition-colors"
                  >
                    Home
                  </Link>
                  <Link
                    href="/About Us"
                    className="text-black transition-colors"
                  >
                    About Us
                  </Link>
                  <Link
                    href="/Achievements"
                    className="text-black transition-colors"
                  >
                    Achievements
                  </Link>
                  <Link
                    href="/Projects"
                    className="text-black transition-colors"
                  >
                    Projects
                  </Link>
                  <Link
                    href="/Donate"
                    className="text-black transition-colors"
                  >
                    Donate
                  </Link>
                </nav>

                {/* Second Row - Copyright Text */}
                <div>
                  <p>© 2024 Your Company. All rights reserved.</p>
                </div>

                {/* Third Row - Developer and Designer Info */}
                <div>
                  <p>
                    Designed by Abimbola | Developed by Ibrahim Adeshina &
                    Kayode Kolawole
                  </p>
                </div>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
